### ISSUE TITLE
Version not printed

### ISSUE THREAD

**Issue by kopardev** [CCBR/RENEE#107]
`renee --version` does not print version number on the head node, but tries to load singularity. I understand that `renee run` etc do require singularity. But `renee --version` should spit out version without the need to load singularity.

### On head node:
<img width="882" alt="image" src="https://github.com/CCBR/RENEE/assets/1882209/c5491d91-9f1e-4f57-9180-cf9406d3e2e7">

### On interactive node:
<img width="538" alt="image" src="https://github.com/CCBR/RENEE/assets/1882209/7de66aa0-291f-408e-8fce-46f0d734ea6c">

**Comment by kopardev** [comment]
`xavier` does something [similar](https://github.com/CCBR/XAVIER/issues/71) but does print version at the bottom line. Also `xavier --help` does this:
<img width="874" alt="image" src="https://github.com/CCBR/RENEE/assets/1882209/42d26e40-13e4-4040-9df8-330cac96e04c">
It complains but also prints the help.

**Comment by kelly-sovacool** [comment]
The modules should only be loaded if they're not already in the path and the platform is either biowulf or FRCE.

The version command works when you call the main driver script `/renee` directly. The problem is in `bin/redirect` (symlinked to `bin/renee`), which contains the logic for loading modules and conda envs. I tend to think we should get rid of these `bin/` files for both xavier and renee (except for maybe the last line to just call the CLI), and instead handle module stuff within run/dryrun subprocesses in the main driver script. Our nextflow template has a simpler design where there's only one `subprocess.run` call that prepends the command with `module load` if needed -- much easier to maintain since there's only one place where nextflow gets called (see https://github.com/CCBR/CCBR_NextflowTemplate/blob/da155de02067db79c0c74013840992739b05de90/src/util.py#L193-L208).

**Comment by kelly-sovacool** [comment]
Work in progress on branch [`iss-107`](https://github.com/CCBR/RENEE/tree/iss-107)

**Comment by kelly-sovacool** [comment]
Idea: what if we handle loading modules and the py311 conda env in the `ccbrpipeliner` module? This way we don't have to write repetitive and hpc-specific code for each pipeline, when they all require most of the same modules anyway (either snakemake or nextflow plus singularity). Most software typically requires users to figure out how to install dependencies with their preferred method anyway, but keeping it in the ccbrpipeliner module allows our biowulf & frce users the extra ease of use of having those dependencies loaded for them.

_Edit: we will implement this in a future release of ccbrpipeliner._ https://github.com/CCBR/ccbrpipeliner/issues/36
