### ISSUE TITLE
RSEQC version on biowulf has been updated

### ISSUE THREAD

**Issue by slsevilla** [CCBR/RENEE#120]
When attempting to run RENEE on biowulf without containers (debugging #119) I found that the RSEQC tool has been updated on Biowulf, making the version in the config outdated.

Need to update tools.json - currently:
```
"RSEQCVER": "rseqc/2.6.4",
```
Available:
```
rseqc/4.0.0    rseqc/5.0.3 (L,D)
```

**Comment by slsevilla** [comment]
hey @tjoshmeyer! Can you do two things:
1) re-run the pipeline as we discussed yesterday (from the edited RENEE without the container, using MODULE LOAD with the updated module version) and let us know if that goes to completion? 
2) Share your ~/.bashrc profile with us? We want to see if there is anything funky that might have pointed the container to the wrong path

Thanks!

**Comment by TJoshMeyer** [comment]
Hi @slsevilla , I just want to confirm:

Should I run RENEE again as before (modified as above) on the same dataset but with a different output directory so that RENEE runs from beginning-to-end for this test?

Or, should I do something to "restart" the run that failed originally?

Thanks!

**Comment by slsevilla** [comment]
> Hi @slsevilla , I just want to confirm:
> 
> Should I run RENEE again as before (modified as above) on the same dataset but with a different output directory so that RENEE runs from beginning-to-end for this test?
> 
> Or, should I do something to "restart" the run that failed originally?
> 
> Thanks!

hey @TJoshMeyer  - you can run it in the same directory that had run before. We're more interested to see what happens with the container than about where it picks up specifically.

**Comment by TJoshMeyer** [comment]
Hi @slsevilla et al.,

I've tried a three more times, but sadly hit failures each time. Details are below:

- Project Directory: ` /data/CCBR/projects/ccbr1327/`
- Attempt 1 Output Directory: `/renee_20240811/`
- Attempt 2 Output Directory: `/renee_20240311/`
- Attempt 3 Output Directory: `/renee_20240318/`

Attempt 1 was originally run on 03/11, though you'll note I mis-dated the directory name. I attempted to restart this run by cloning and modifying RENEE as you taught me to remove the Docker line from the TIN rule. That re-run attempt failed.

Attempt 2 was an attempt to use the same modified clone of RENEE to just start over at the beginning, rather than pick up where it failed the first time in 1. This attempt also failed.

Atttempt 3 was run using RENEE in the latest 'module load' version of pipeliner on Biowulf, using standard RENEE documentation to begin the run. Unfortunately, this 'ml' version also failed.

If your bandwidth allows, and if there's a way for me to get this dataset analyzed today, I'd like your advice on how to do it. The collaborator has a lab meeting Thursday and would love initial results if I can get them to him. I understand if there's not time to resolve this before then, though. Thanks in advance for any help.

**Comment by TJoshMeyer** [comment]
Oh, and you asked about my ~/.bashrc file. Here is what I have on Biowulf:

```
[meyertj@biowulf ~]$ cat .bashrc
# .bashrc

# Source global definitions:

if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions:

alias ls='ls --color=auto'
alias ll='ls -lah'

if [ -f /data/CCBR/init/ccbrbash ]; then
	.  /data/CCBR/init/ccbrbash
fi
```
And, in case it's relevant, I also found that I have a ~/.bash_profile, too. Here's that one:

```
[meyertj@biowulf ~]$ cat .bash_profile 
# .bash_profile

# Get the aliases and functions:

if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs:

PATH=$PATH:$HOME/bin

export PATH
```

I hope this helps. Thanks!

**Comment by slsevilla** [comment]
Reviewing failures

## Failure 1
This failed due to missing the tin.py
```
/bin/bash: line 3: tin.py: command not found
```

Looks like the module still didn't get loaded, even with the edits.

**Comment by kelly-sovacool** [comment]
> Reviewing failures
> 
> ## Failure 1
> This failed due to missing the tin.py
> 
> ```
> /bin/bash: line 3: tin.py: command not found
> ```
> 
> Looks like the module still didn't get loaded, even with the edits.

the problem is the container didn't have tin.py and other rseqc scripts in the path -- I've fixed this with https://github.com/CCBR/Dockers/pull/31

**Comment by kelly-sovacool** [comment]
> When attempting to run RENEE on biowulf without containers (debugging #119) I found that the RSEQC tool has been updated on Biowulf, making the version in the config outdated.
> 
> Need to update tools.json - currently:
> 
> ```
> "RSEQCVER": "rseqc/2.6.4",
> ```
> 
> Available:
> 
> ```
> rseqc/4.0.0    rseqc/5.0.3 (L,D)
> ```

the docker container uses v4.0.0 anyway, so it'll be good to sync them up
